### PR TITLE
St make valid

### PR DESCRIPTION
**Pull request by osymandius**
Fix geometry errors in survey region boundaries

### CODE REVIEW

**Comment by jeffeaton** [comment]
Thanks very much. Can you give a reproducible example on the issue?

**Comment by osymandius** [comment]
```
iso3 <- "ZMB"

areas <- sharepoint_areas_link
areas_wide <- spread_areas(areas)

surveys <- create_surveys_dhs(iso3, survey_characteristics = NULL) %>%
  filter(as.numeric(SurveyYear) > 1994)

survey_meta <- create_survey_meta_dhs(surveys)

survey_region_boundaries <- create_survey_boundaries_dhs(surveys)
surveys <- surveys_add_dhs_regvar(surveys, survey_region_boundaries)

## Line throws an error
survey_region_areas <- allocate_areas_survey_regions(areas_wide, survey_region_boundaries)

## Debug: 
survey_split <- survey_region_boundaries %>%
  group_split(survey_id)

lapply(survey_split, sf::st_is_valid)
```

**Comment by osymandius** [comment]
Also in similar vein - invalid geometries within our shapefiles. 

areas <- sharepoint_areas_link_for_TZA
areas_wide <- spread_areas(areas)
st_is_valid(areas_wide)

@rtesra have you encountered this?

**Comment by jeffeaton** [comment]
Thanks for finding this. The issue here is with the survey boundaries from the DHS Spatial Data Repository, but I think it is pretty infrequent. I propose that we fix data errors in the processing script rather than patch in the functions. See below -- what do you think?

```
iso3 <- "ZMB"

areas <- read_sf("depends/zmb_areas.geojson")
areas_wide <- spread_areas(areas)

surveys <- create_surveys_dhs(iso3, survey_characteristics = NULL) %>%
  filter(as.numeric(SurveyYear) > 1994)
survey_region_boundaries <- create_survey_boundaries_dhs(surveys)
surveys <- surveys_add_dhs_regvar(surveys, survey_region_boundaries)

#REGVAR for ZMB2013DHS is incorrectly coded as v024, should be hv024
surveys$REGVAR[surveys$survey_id == "ZMB2013DHS"] <- "hv024"

survey_region_boundaries <- st_make_valid(survey_region_boundaries)

survey_region_areas <- allocate_areas_survey_regions(areas_wide, survey_region_boundaries)
```

Re Tanzania, argh. I thought we'd fixed that one in the dataset last year. Will have a look.

**Pull request closed without merging**
